// This file was autogenerated by calcdeps.py
goog.addDependency("../cmn/cmn.js", ['cmn.getDateTime', 'cmn.cutText'], []);
goog.addDependency("../controllers/cmn.js", [], []);
goog.addDependency("../controllers/drag_and_drop.js", ['controller.drag_n_drop'], ['controller.lets_rock', 'view.view']);
goog.addDependency("../controllers/lets_rock.js", ['controller.lets_rock', 'controller.animate', 'controller.stop_lets_rock'], []);
goog.addDependency("../controllers/menu.js", ['controller.show_menu'], []);
goog.addDependency("base.js", [], []);
goog.addDependency("base_ex.js", [], []);
goog.addDependency("deps.js", [], []);
goog.addDependency("jquery-ui.js", [], []);
goog.addDependency("jquery.js", [], []);
goog.addDependency("../views/cmn.js", ['view.view'], []);

